<?php

class ErrorCode
{
	const USERNAME_EXISTS = 1;
	const PASSWORD_CANNOT_EMPTY = 2;
	const USERNAME_CANNOT_EMPTY = 3;
	const REGISTER_FAIL = 4;
	const USERNAME_OR_PASSWORD = 5;

	const TITLE_CANNOT_EMPTY = 6;
	const CONTENT_CANNOT_EMPTY = 7;
	const ARTICLE_CREATE_FAIL = 8;
	const ARTICLE_NOT_FOUND = 8;
	const SERVER_ERROR = 9;
}